
FROM astrocrpublic.azurecr.io/runtime:3.0-12

# Install additional Python packages if needed
# COPY requirements.txt .
# RUN pip install -r requirements.txt

# Copy Google ADC credentials into the container (optional for local dev)
# Uncomment the following lines if you have Google Cloud credentials to copy
# COPY ./.config/gcloud/application_default_credentials.json /home/astro/.config/gcloud/application_default_credentials.json
