
FROM astrocrpublic.azurecr.io/runtime:3.0-12

# Copy Google ADC credentials into the container
COPY ./.config/gcloud/application_default_credentials.json /home/astro/.config/gcloud/application_default_credentials.json
